# theme: jekyll-theme-minimal
theme: "minima"
  skin: "dark"
title: lg's blog
description: musings on infosec and tech

header_pages:
  - about.md


rss: rss

  # kramdown:
  #   syntax_highlighter_opts:
  #     disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
